### ISSUE TITLE
K0080.xml

### ISSUE THREAD

**Issue by ajaniak** [erc-dharma/tfc-khmer-epigraphy#19]
Dear @chhomkunthea,

There is a version conflict on your file K0080.xml.  It starts with such a pattern  `<<<<<<< HEAD` and says that 2 versions of the same part of the file coexist. Can you check it and keep only the one you want in the file? 
Note that there are currently 2 conflicts in the file: one in the apparatus and one in the translation. 
Thanks for your help

**Comment by arlogriffiths** [comment]
Since Kunthea has probably never yet resolved such a conflict, she may need help.

Could you arrange a skype/zoom session?



Le 12 nov. 2020 à 09:49, ajaniak <notifications@github.com<mailto:notifications@github.com>> a écrit :



Dear @chhomkunthea<https://github.com/chhomkunthea>,

There is a version conflict on your file K0080.xml. It starts with such a pattern <<<<<<< HEAD and says that 2 versions of the same part of the file coexist. Can you check it and keep only the one you want in the file?
Note that there are currently 2 conflicts in the file: one in the apparatus and one in the translation.
Thanks for your help

**Comment by chhomkunthea** [comment]
Dear Axelle and Arlo,

I’ve solved the problems of K. 80.xml and pushed the file on Github. It’s green now; hope that it’s alright.

Best,
Kunthea

**Comment by ajaniak** [comment]
Great, thanks @chhomkunthea
