### ISSUE TITLE
DHARMA_INSCIK00172 - Zotero Validation Issue

### ISSUE THREAD

**Issue by ajaniak** [erc-dharma/tfc-khmer-epigraphy#25]
Dear @chloechollet, 

In your edition of K. 172, you are using the Zotero Short Title `Coedes1911_01`. It matches 2 entries in Zotero Library: _« Études Cambodgiennes : 2. Une inscription du sixième siècle çaka, 3. Une nouvelle inscription du Phnoṃ Bàkheṅ, IK 496, 4. La grotte de Pơṅ Práḥ Thvãr (Phnoṃ Kulèn), 5. Une inscription d’Udayādityavarman I, 6. Des édicules appelés “bibliothèques” », Bulletin de l’École française d’Extrême-Orient 11 (3-4), p. 393-396, 396-398, 398-400, 400-404, 405-406, [Réimpr. 1989, APK 1, p. 3-6, 6-8, 8-10, 10-15, 15-16]._ and _Etudes cambodgiennes I: la légende de la Nāgī_. 
Can you see if it is possible to resolve this? 

Thank you for your help.
Best

**Comment by chloechollet** [comment]
Dear @ajaniak 
I just checked the two Zotero entries and the first one (Études Cambodgiennes : 2. [...]) bears the Short Title Coedes1911_01 ; and the second one (Les deux inscriptions de Vat Thipdei) has the Short Title Coedes1911_02 ... I then don't understand where the issue comes from ! Do you have any idea ?
Thank you,
Chloé

**Comment by ajaniak** [comment]
Weird because I see both as Coedes1911_01 and Coedes1911_02 matches _Les bas-reliefs d'Ankor-Vat_
See the citekey which is set on the short Title field value

<img width="801" alt="Capture d’écran 2021-04-09 à 12 28 22" src="https://user-images.githubusercontent.com/33328906/114167370-26e53400-992f-11eb-9ac5-428f129c5562.png">

Can you check that your synchronization works?

**Comment by chloechollet** [comment]
I found them ! For some reason, the four references did not appear in E-Cambodia for me, but in the general repository of ERC-DHARMA. I've now changed the Short Titles ! Can you tell me if it worked ? I will also change the reference in K. 172.

**Comment by arlogriffiths** [comment]
Chloé: when searching what is the correct short title, you should always position yourself at ther top level (ERC-DHARMA), rather than in the most relevant subcollection (E-Cambodia).


Le 9 avr. 2021 à 12:36, chloechollet ***@***.******@***.***>> a écrit :



I found them ! For some reason, the four references did not appear in E-Cambodia for me, but in the general repository of ERC-DHARMA. I've now changed the Short Titles ! Can you tell me if it worked ? I will also change the reference in K. 172.

**Comment by ajaniak** [comment]
Yes, it worked. Thanks for your help
