### ISSUE TITLE
DHARMA_INSCIK00293-5 - Zotero Short Title Issue

### ISSUE THREAD

**Issue by ajaniak** [erc-dharma/tfc-khmer-epigraphy#30]
Dear @chhomkunthea, 

In your edition of K 293-5, you have used the Zotero Short Title `Coedes1928_01`. It matches 2 entries in Zotero _Études Cambodgiennes : 19. La date du Bàyon, 20. Les capitales de Jayavarman II », Bulletin de l’École française d’Extrême-Orient 28 (1-2), p. 81-112, 113-123, [Réimpr. 1989, APK 1, p. 95-117, 127-137]._ and _L’inscription de Tuol Komnap Ta Kin_. Can you check this please? 

Thanks

**Comment by chhomkunthea** [comment]
Dear Axelle,

The one we need is :

Études Cambodgiennes : 19. La date du Bàyon, 20. Les capitales de Jayavarman II », Bulletin de l’École française d’Extrême-Orient 28 (1-2), p. 81-112, 113-123, [Réimpr. 1989, APK 1, p. 95-117, 127-137]

I have changed the other one (L’inscription de Tuol Komnap Ta Kin) into Coedès1928_02.
But the xml file is still red with the comment that the short title matches several entries in the Zotero. I think that my change has not been taken into account. Maybe you told me before how to update the short title but I forgot. Sorry! Please tell me again if you don't mind!

See you!

**Comment by arlogriffiths** [comment]
I think it is because you have only modified the short title in the Short Title field. You should make the corresponding change under Tags, changing 01 to 02. See screenshot for where to make the change:

<img width="983" alt="Capture d’écran 2021-04-13 à 19 28 09" src="https://user-images.githubusercontent.com/835603/114595371-9a1fda80-9c8e-11eb-995d-bb0c151befa0.png">


@chloechollet and @salomepichon : please take a look at this and other current issues at [https://github.com/erc-dharma/tfc-khmer-epigraphy/issues/](https://github.com/erc-dharma/tfc-khmer-epigraphy/issues/) so you know how to fix such problems.

**Comment by chhomkunthea** [comment]
That was the trick! Thank you very much!
